import { randomUUID } from 'node:crypto';
import Anthropic from '@anthropic-ai/sdk';
import type { Request, Response, NextFunction } from 'express';
import type { TenantRequest } from '../middleware/tenant.js';

/**
 * Error handling and request correlation.
 *
 * The previous handler ended with:
 *
 *     res.status(500).json({ error: message || 'Internal server error' });
 *
 * where `message` was the raw `Error.message`. That leaks whatever the thrower
 * happened to include — SQL fragments and column names from pg, full upstream
 * response bodies from Shopify/Meta/Anthropic, absolute filesystem paths from
 * fs errors, and occasionally credentials embedded in a connection string. It
 * also gave the caller nothing to quote when reporting a problem, and the server
 * log had no key to find the matching entry.
 *
 * Now: the caller gets a stable, generic message plus a request id; the log gets
 * everything, tagged with the same id.
 */

export interface RequestWithId extends Request {
  requestId: string;
}

/** Assigns an id to every request and echoes it, so a client can quote it. */
export function attachRequestId(req: Request, res: Response, next: NextFunction): void {
  // Honour an inbound id so a trace survives the Next.js proxy hop, but bound
  // the length — it goes into logs and a response header.
  const inbound = req.header('x-request-id')?.trim();
  const id =
    inbound && inbound.length <= 64 && /^[\w.-]+$/.test(inbound) ? inbound : randomUUID();
  (req as RequestWithId).requestId = id;
  res.setHeader('X-Request-Id', id);
  next();
}

/**
 * Errors whose message is written for the user and safe to return verbatim.
 *
 * The codebase throws plain `Error` for both programmer faults and deliberate
 * user-facing refusals — "Shopify is not connected", "Product SEO daily cap
 * reached", "This product was SEO-updated within the last 7 days". Those are the
 * whole point of the human gates and must survive to the UI, so match them
 * explicitly rather than passing every message through.
 */
const SAFE_MESSAGE_PATTERNS: RegExp[] = [
  /is not connected/i,
  /not connected for this workspace/i,
  /missing [\w_]+ scope/i,
  /daily cap reached/i,
  /cooldown/i,
  /within the last \d+ days/i,
  /already (running|claimed|in flight)/i,
  /Cannot (approve|skip|rollback) execution in status/i,
  /require(s)? approval/i,
  /not found$/i,
  /Execution not found/i,
  /do not have access/i,
  /is required$/i,
  /Too many/i,
  /goal is already met/i,
  /awaiting (human|your) (action|review)/i,
  /verify upstream state/i,
];

function isSafeMessage(message: string): boolean {
  if (message.length > 300) return false;
  return SAFE_MESSAGE_PATTERNS.some((re) => re.test(message));
}

type MaybeStatused = Error & {
  status?: number;
  statusCode?: number;
  issues?: unknown;
};

export function errorHandler(
  err: MaybeStatused,
  req: Request,
  res: Response,
  _next: NextFunction
): void {
  const requestId = (req as RequestWithId).requestId ?? 'unknown';
  const tenant = (req as TenantRequest).tenant;
  const message = err instanceof Error ? err.message : String(err);

  // Full detail server-side only, keyed by the id the caller was given.
  console.error(
    `[error] id=${requestId} ${req.method} ${req.originalUrl}` +
      (tenant?.id ? ` org=${tenant.id}` : '') +
      `\n        ${err?.name ?? 'Error'}: ${message}` +
      (err?.stack ? `\n${err.stack.split('\n').slice(1, 6).join('\n')}` : '')
  );

  if (res.headersSent) return;

  // Validation — the field paths are generated by our own schemas, not by the
  // upstream, so they are safe and genuinely useful.
  if (err?.name === 'ZodError') {
    res.status(400).json({
      error: 'Validation failed',
      details: err.issues,
      requestId,
    });
    return;
  }

  // MCP connector failures. Kept as a distinct 502 with actionable wording,
  // matching the previous behaviour.
  if (
    err instanceof Anthropic.APIError
      ? /MCP server|communicating with MCP/i.test(message)
      : /MCP server|communicating with MCP/i.test(message)
  ) {
    res.status(502).json({
      error:
        'A connector failed to respond. Restart the API and try again — plans fall back to direct API data.',
      requestId,
    });
    return;
  }

  // Upstream provider errors: report the class, never the body. An Anthropic or
  // Shopify error body can contain the request we sent, including prompt text.
  if (err instanceof Anthropic.APIError) {
    const status = err.status && err.status >= 500 ? 502 : 502;
    res.status(status).json({
      error: 'The AI provider returned an error. Try again shortly.',
      requestId,
    });
    return;
  }

  // Explicit status set by a route, e.g. 401/403/404.
  const explicit = err.status ?? err.statusCode;
  if (explicit && explicit >= 400 && explicit < 500) {
    res.status(explicit).json({
      error: isSafeMessage(message) ? message : 'Request rejected',
      requestId,
    });
    return;
  }

  // Deliberate, user-facing refusals thrown as plain Errors.
  if (isSafeMessage(message)) {
    res.status(400).json({ error: message, requestId });
    return;
  }

  // Everything else is a fault. Generic body, id to correlate.
  res.status(500).json({
    error: 'Something went wrong on our side. Quote the request id if you report this.',
    requestId,
  });
}
